export type Base64CharValue = {
    char: string;
    value: number;
};

export const BASE64_MAP: Base64CharValue[] = [
    { char: "A", value: 0 },
    { char: "B", value: 1 },
    { char: "C", value: 2 },
    { char: "D", value: 3 },
    { char: "E", value: 4 },
    { char: "F", value: 5 },
    { char: "G", value: 6 },
    { char: "H", value: 7 },
    { char: "I", value: 8 },
    { char: "J", value: 9 },
    { char: "K", value: 10 },
    { char: "L", value: 11 },
    { char: "M", value: 12 },
    { char: "N", value: 13 },
    { char: "O", value: 14 },
    { char: "P", value: 15 },
    { char: "Q", value: 16 },
    { char: "R", value: 17 },
    { char: "S", value: 18 },
    { char: "T", value: 19 },
    { char: "U", value: 20 },
    { char: "V", value: 21 },
    { char: "W", value: 22 },
    { char: "X", value: 23 },
    { char: "Y", value: 24 },
    { char: "Z", value: 25 },

    { char: "a", value: 26 },
    { char: "b", value: 27 },
    { char: "c", value: 28 },
    { char: "d", value: 29 },
    { char: "e", value: 30 },
    { char: "f", value: 31 },
    { char: "g", value: 32 },
    { char: "h", value: 33 },
    { char: "i", value: 34 },
    { char: "j", value: 35 },
    { char: "k", value: 36 },
    { char: "l", value: 37 },
    { char: "m", value: 38 },
    { char: "n", value: 39 },
    { char: "o", value: 40 },
    { char: "p", value: 41 },
    { char: "q", value: 42 },
    { char: "r", value: 43 },
    { char: "s", value: 44 },
    { char: "t", value: 45 },
    { char: "u", value: 46 },
    { char: "v", value: 47 },
    { char: "w", value: 48 },
    { char: "x", value: 49 },
    { char: "y", value: 50 },
    { char: "z", value: 51 },

    { char: "0", value: 52 },
    { char: "1", value: 53 },
    { char: "2", value: 54 },
    { char: "3", value: 55 },
    { char: "4", value: 56 },
    { char: "5", value: 57 },
    { char: "6", value: 58 },
    { char: "7", value: 59 },
    { char: "8", value: 60 },
    { char: "9", value: 61 },

    { char: "+", value: 62 },
    { char: "/", value: 63 },
];
